### ISSUE TITLE
Readme.md contents are old

### ISSUE THREAD

**Issue by ymasaoka** [AzureCosmosDB/labs#12]
[https://github.com/AzureCosmosDB/labs/blob/master/readme.md](https://github.com/AzureCosmosDB/labs/blob/master/readme.md)

With the commit of 27e0721, the content of .NET Labs has changed for C# 8.0.
It does not work with .NET Core 2.1. C# 8.0 has been supported since .NET Core 3.1.
Please correct the download link etc.

**Comment by ymasaoka** [comment]
In the commit below by @markjbrown , I have confirmed that the abbreviation for using has been deleted and that the CosmosClient has been changed to static.
6693a693efc7f53c4ec79f3cbba527b275a79f81

**Comment by markjbrown** [comment]
.NET Core 2.1 was deprecated in December 2019 which is why this lab has been migrated to .NET Core 3.1 and C# 8.0.

Thanks.
