### ISSUE TITLE
The screen of 03-adf_source_next.jpg may have been updated

### ISSUE THREAD

**Issue by ymasaoka** [AzureCosmosDB/labs#14]
> Un-check **Copy file recursively** or **Binary Copy** if they are checked. Also ensure that other fields are empty.

The screen contents have changed, and "Copy file recursively" has changed to "Recursively".
Please check and correct if necessary.
![image.png](https://user-images.githubusercontent.com/46888598/91207110-379bbd80-e743-11ea-8f27-92ae4719b16a.png)

**Comment by markjbrown** [comment]
Updated.
