### ISSUE TITLE
The screen of 03-adf_destinationconnectionfinal.jpg  was not displayed

### ISSUE THREAD

**Issue by ymasaoka** [AzureCosmosDB/labs#15]
I did the lab contents of 02-load_data_with_adf.md, but the screen of 03-adf_destinationconnectionfinal.jpg was not displayed.
Maybe there are updates.
For reference, it was that the display on the previous screen was partly different.

![image2.png](https://user-images.githubusercontent.com/46888598/91208101-a3caf100-e744-11ea-8edf-ea62bd5a2acd.png)

**Comment by markjbrown** [comment]
I'm not clear what you are asking here. Can you clarify?
