### ISSUE TITLE
The screen of 03-adf_selections.jpg is old and needs to be updated

### ISSUE THREAD

**Issue by ymasaoka** [AzureCosmosDB/labs#17]
[https://github.com/AzureCosmosDB/labs/blob/master/dotnet/labs/02-load_data_with_adf.md](https://github.com/AzureCosmosDB/labs/blob/master/dotnet/labs/02-load_data_with_adf.md)
[https://github.com/AzureCosmosDB/labs/blob/master/dotnet/media/03-adf_selections.jpg](https://github.com/AzureCosmosDB/labs/blob/master/dotnet/media/03-adf_selections.jpg)

The following sentences explained on the above page do not fit the latest Azure portal display.

> Do not select Enable GIT (this may be checked by default).

Now there are **Basic** and **Git configuration** tabs.
Please update to match the latest Azure portal display.

*NOTE: Japanese is mixed in the image.*

![screenshot_1](https://user-images.githubusercontent.com/46888598/91337728-ca555e80-e80e-11ea-8623-28f637813d12.png)
![screenshot_2](https://user-images.githubusercontent.com/46888598/91337733-cb868b80-e80e-11ea-9030-8b0ac8959577.png)

**Comment by markjbrown** [comment]
Updated.
