### ISSUE TITLE
Typo with date as data

### ISSUE THREAD

**Issue by ymasaoka** [AzureCosmosDB/labs#19]
[/labs/dotnet/labs/02-load_data_with_adf.md](https://github.com/AzureCosmosDB/labs/blob/master/dotnet/labs/02-load_data_with_adf.md)

- [Import Lab Data Into Container](https://github.com/AzureCosmosDB/labs/blob/master/dotnet/labs/02-load_data_with_adf.md#import-lab-data-into-container)

> 18. Select your newly created targetcosmosdb connection as the Destination date store.

It's a data store, not a date store.

**Comment by markjbrown** [comment]
Updated.
